sudo: required
dist: trusty
language: cpp
cache: ccache

before_script:
  # Start in the parent directory of icub-model-generator 
  - cd ..
  - sudo apt-get install  --assume-yes --force-yes python-lxml python-yaml python-numpy python-setuptools
  # probably python on the path return a python interpreter and the find_package(PythonInterp) in CMake another, 
  # let's install both debian packages and pip packages to be sure
  - pip install lxml numpy pyyaml 
  # install urdf_parser_py
  - git clone https://github.com/ros/urdf_parser_py
  - cd urdf_parser_py
  - python setup.py install
  - cd ../
  # install simmechanics-to-urdf
  - git clone https://github.com/robotology/simmechanics-to-urdf
  - cd simmechanics-to-urdf
  - python setup.py install
  - cd ../
  # use superbuild for getting icub-model-generator C++ dependencies
  - git clone https://github.com/robotology/codyco-superbuild
  - cd codyco-superbuild
  # install dependencies using the codyco-superbuild script
  - chmod +x ./.ci/travis-deps.sh
  - sh .ci/travis-deps.sh
  - mkdir build
  - cd build
  - export CMAKE_PREFIX_PATH=`pwd`/install
  # using the YCM_EP_MAINTAINER_MODE variable to enable the subproject-dependees target
  - cmake -DCODYCO_TRAVIS_CI:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DYCM_EP_MAINTAINER_MODE:BOOL=ON -DNON_INTERACTIVE_BUILD:BOOL=TRUE  ..
  - cmake --build .
  - pwd
  - cd ../..
  # Prepare icub-model-generator build
  - cd icub-model-generator 
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
  - ctest --output-on-failure

notifications:
  email:
    - pegua1@gmail.com
