sudo: required
dist: trusty
language: cpp
cache: ccache

before_script:
  # workaround around opencv linking problem in clang:
  # http://stackoverflow.com/questions/12689304/ctypes-error-libdc1394-error-failed-to-initialize-libdc1394
  - sudo ln /dev/null /dev/raw1394
  - cmake --version
  - cd ..
  # use superbuild for getting icub-model-generator dependencies
  - git clone https://github.com/robotology/codyco-superbuild
  - cd codyco-superbuild
  # install dependencies using the codyco-superbuild script
  - chmod +x ./.ci/travis-deps.sh
  - sh .ci/travis-deps.sh
  - mkdir build
  - cd build
  - export CMAKE_PREFIX_PATH=`pwd`/install
  # using the YCM_EP_MAINTAINER_MODE variable to enable the subproject-dependees target
  - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCODYCO_TRAVIS_CI:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DYCM_EP_MAINTAINER_MODE:BOOL=ON -DNON_INTERACTIVE_BUILD:BOOL=TRUE  ..
  - cmake --build .
  - pwd
  - cd ../..
  # Prepare icub-model-generator build
  - cd idyntree
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
  - ctest --output-on-failure

notifications:
  email:
    - pegua1@gmail.com
